import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { getUserFromRequest } from '@/lib/api/getUser'

// POST /api/sessions/[id]/invites — Create a new invite link
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: sessionId } = await params

  const user = await getUserFromRequest(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = await createAdminClient()

  // Verify caller is primary host or admin
  const { data: session } = await admin
    .from('sessions')
    .select('id, host_id')
    .eq('id', sessionId)
    .single()

  if (!session) {
    return NextResponse.json({ error: 'Session not found' }, { status: 404 })
  }

  const { data: profile } = await admin
    .from('profiles')
    .select('is_admin')
    .eq('id', user.id)
    .single()

  if (session.host_id !== user.id && !profile?.is_admin) {
    return NextResponse.json({ error: 'Only the primary host or admin can create invites' }, { status: 403 })
  }

  // Create invite (token is auto-generated by DB default)
  const { data: invite, error } = await admin
    .from('cohost_invites')
    .insert({
      session_id: sessionId,
      created_by: user.id,
    })
    .select('id, token, expires_at, created_at')
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(invite, { status: 201 })
}

// GET /api/sessions/[id]/invites — List invites for a session
export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: sessionId } = await params

  const user = await getUserFromRequest(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = await createAdminClient()

  // Verify caller is primary host or admin
  const { data: session } = await admin
    .from('sessions')
    .select('id, host_id')
    .eq('id', sessionId)
    .single()

  if (!session) {
    return NextResponse.json({ error: 'Session not found' }, { status: 404 })
  }

  const { data: profile } = await admin
    .from('profiles')
    .select('is_admin')
    .eq('id', user.id)
    .single()

  if (session.host_id !== user.id && !profile?.is_admin) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { data: invites, error } = await admin
    .from('cohost_invites')
    .select('id, token, status, expires_at, created_at, accepted_at, accepted_by, created_by')
    .eq('session_id', sessionId)
    .order('created_at', { ascending: false })

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(invites)
}
